services:
  - type: web
    name: next-js
    runtime: node
    plan: starter
    buildCommand: yarn set version 4.9.1 && yarn install --immutable && yarn build
    startCommand: yarn start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 23.11.0
