name: Run Ingest

on:
  workflow_dispatch: # Run manually

jobs:
  ingest:
    if: github.actor == secrets.DISPATCH_ALLOWED_ACTOR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run ingest script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: yarn run ingest
